### PR TITLE
training speed up

### PR DESCRIPTION
**Pull request by tartavull**
Did some little cleaning and speed ups

### CODE REVIEW

**Comment by yenchenlin** [comment]
Hello @tartavull , thanks a lot for this! 🙌 
Can you briefly describe the improvement?

Also, is there any document to support [this line](https://github.com/yenchenlin/pix2pix-tensorflow/pull/5/files#diff-93ff136fae812392eb0f68d1ce89b7feR146)?

**Comment by tartavull** [comment]
I've basically merged all the sess.run() into one single call, so that we don't have to recompute the losses multiple time.

The reasons of training the generator twice for every time we train the discriminator is to try to keep the losses balanced. That line makes it more explicit, and works well in practice in my experience.

**Comment by jpapon** [comment]
Typo here: https://github.com/yenchenlin/pix2pix-tensorflow/pull/5/files#diff-93ff136fae812392eb0f68d1ce89b7feR174

**Comment by yenchenlin** [comment]
@jpapon eagle eye!
@tartavull I'll test this on my computer and get back to you soon.
It looks good to me, thanks again!

**Comment by tartavull** [comment]
Now it is way faster than before

**Comment by tartavull** [comment]
although I have broken a few things in the way, like the test phase

**Comment by tartavull** [comment]
let me fix all this first, and do another PR later on

**Comment by yenchenlin** [comment]
@tartavull thanks a lot!
Really looking forward to it.

**Pull request closed without merging**
